Operaciones Elementales
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/02.03-operaciones-elementales.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/02.03-operaciones-elementales.ipynb) para ver la última versión online en `nbviewer`. 

---

Para el siguiente sistema lineal, elimine $x_1$ de todas las ecuaciones excepto la primera.

$$ 
\begin{array}{cccccc}
  2x_1 & +3x_2 & -4x_3 &  +x_4 & = & 1\\
   x_1 &  -x_2 &       & +5x_4 & = & 6\\
  3x_1 &  +x_2 &  +x_3 &       & = & 2\\
\end{array}
$$

Para poder realizar simultaneamente los cálculos con Python, se carga la librería `
numpy`.

In [13]:
import numpy as np

Se representa el sistema de ecuaciones como una matriz. Verifique que la matriz representa el problema anterior.

In [14]:
a = np.matrix('2. 3 -4 1 1; 1 -1 0 5 6; 3 1 1 0 2')
a

matrix([[ 2.,  3., -4.,  1.,  1.],
        [ 1., -1.,  0.,  5.,  6.],
        [ 3.,  1.,  1.,  0.,  2.]])

**Paso 1.** Se divide $E_1$ por 2:

$$
\begin{array}{cccccc}
   x_1 & +\frac{3}{2} x_2 & -2x_3 &  +\frac{1}{2}x_4 & = & \frac{1}{2}\\
   x_1 &  -x_2 &       & +5x_4 & = & 6\\
  3x_1 &  +x_2 &  +x_3 &       & = & 2\\
\end{array}
$$

In [10]:
a[0,:] = a[0,:] / 2
a

matrix([[ 1. ,  1.5, -2. ,  0.5,  0.5],
        [ 1. , -1. ,  0. ,  5. ,  6. ],
        [ 3. ,  1. ,  1. ,  0. ,  2. ]])

**Paso 2.** Se divide $E'_1$ por -1 y se suma a $E_2$:

$$
\begin{array}{cccccc}
   x_1 & +\frac{3}{2} x_2 & -2x_3 &  +\frac{1}{2}x_4 & = & \frac{1}{2} \\
       & -\frac{5}{2} x_2 & +2x_3 & + \frac{9}{2}x_4 & = & \frac{11}{2}\\
  3x_1 &  +x_2 &  +x_3 &       & = & 2\\
\end{array}
$$

In [11]:
a[1,:] = a[1,:] + (-1) * a[0,:]
a

matrix([[ 1. ,  1.5, -2. ,  0.5,  0.5],
        [ 0. , -2.5,  2. ,  4.5,  5.5],
        [ 3. ,  1. ,  1. ,  0. ,  2. ]])

**Paso 3.** Se divide $E'_1$ por -3 y se suma a $E_3$:

$$
\begin{array}{cccccc}
   x_1 & +\frac{3}{2} x_2 & -2x_3 &  +\frac{1}{2} x_4 & = & \frac{1}{2}  \\
       & -\frac{5}{2} x_2 & +2x_3 &  +\frac{9}{2} x_4 & = & \frac{11}{2} \\
       & -\frac{7}{2} x_2 & +7x_3 &  -\frac{3}{2} x_4 & = & \frac{1}{2}  \\
\end{array}
$$

In [12]:
a[2,:] = a[2,] + (-3) * a[0,]
a

matrix([[ 1. ,  1.5, -2. ,  0.5,  0.5],
        [ 0. , -2.5,  2. ,  4.5,  5.5],
        [ 0. , -3.5,  7. , -1.5,  0.5]])

**Ejercicio.--** Elimine $x_2$ de las ecuaciones 1 y 3.

**Ejercicio.--** Elimine $x_3$ de las ecuaciones 1 y 2.

Operaciones Elementales
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/02.03-operaciones-elementales.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/02.03-operaciones-elementales.ipynb) para ver la última versión online en `nbviewer`. 

---