Forma Estándar
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/04-forma-estandar.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/04-forma-estandar.ipynb) para ver la última versión online en `nbviewer`. 

---

En la forma estándar todas las restricciones son transformadas a igualdades con los $b_i \ge 0$. Sea el modelo:

$$
\text{min } \sum_{j=1}^m c_j x_j
$$
 
Sujeto a:

$$
\sum_{j=1}^n a_{ij} x_j = b_i \text{   para   } i = 1, ..., m
$$

$$
 x_j \ge 0 \text{   para   } j = 1, ..., n
$$

Forma matricial:

$$ \text{min   } z = c~x \qquad \text{s/a: } Ax = b, \quad ~~x \ge 0$$

**Transformación de un problema a la forma estándar**.

Si la $i$-ésima restricción es $\le$, se le suma una variable adicional $x_{n+i}$:

$$
\sum_{j=1}^n a_{ij} x_j \le b_i ~~\rightarrow  ~~ \sum_{j=1}^n a_{ij} x_j + x_{n+i} = b_i
$$

Si la $i$-ésima restricción es $\ge$, se le resta una variable adicional $x_{n+i}$:

$$
\sum_{j=1}^n a_{ij} x_j \ge b_i ~~\rightarrow  ~~ \sum_{j=1}^n a_{ij} x_j - x_{n+i} = b_i
$$

Si la $i$-ésima variable tiene restricción de signo: $-\infty < x_i < \infty$, se reemplaza $x_i = x_i' - x_i''$

**Ejemplo**

Función objetivo:

$$\text{min } z = x_1 + x_2$$

Sujeto a:
$$ 
\begin{array}{cccc}
   2x_1 & +3~x_2 & \le & 6\\
    x_1 & +7~x_2 & \ge & 4\\
    x_1 &   +~
x_2 & =   & 3\\
\end{array}
$$

con: $x_1 \ge 0$, $-\infty < x_2 < \infty$.

**Paso 1**. Se representa el problema en forma matricial:

In [1]:
import numpy as np

In [2]:
m = np.matrix('2. 3 0 6; 1 7 0 4; 1 1 0 3; 1 1 -1 0')
m

matrix([[ 2.,  3.,  0.,  6.],
        [ 1.,  7.,  0.,  4.],
        [ 1.,  1.,  0.,  3.],
        [ 1.,  1., -1.,  0.]])

**Nota**: la última fila de la matriz corresponde a la función objetivo $x_1 + x_2 - z = 0$. 

**Paso 2.** Se adiciona la variable de holgura $x_3$ a la primera restricción. 

In [3]:
m = np.c_[m[:,[0,1]], np.matrix('1; 0; 0; 0'), m[:, [2,3]]]
m

matrix([[ 2.,  3.,  1.,  0.,  6.],
        [ 1.,  7.,  0.,  0.,  4.],
        [ 1.,  1.,  0.,  0.,  3.],
        [ 1.,  1.,  0., -1.,  0.]])

**Paso 3.** Se resta la variable de holgura $x_4$ de la segunda restricción.

In [4]:
m = np.c_[m[:,[0,1,2]], np.matrix('0; -1; 0; 0'), m[:, [-2,-1]]]
m

matrix([[ 2.,  3.,  1.,  0.,  0.,  6.],
        [ 1.,  7.,  0., -1.,  0.,  4.],
        [ 1.,  1.,  0.,  0.,  0.,  3.],
        [ 1.,  1.,  0.,  0., -1.,  0.]])

**Paso 4.** Se reemplaza $x_2$ por $x_2' - x_2''$. Esto equivale a agregar la variable $x_5 = -x_2$.

In [5]:
m = np.c_[m[:,[0,1,2,3]], -m[:,1], m[:, [-2,-1]]]
m

matrix([[ 2.,  3.,  1.,  0., -3.,  0.,  6.],
        [ 1.,  7.,  0., -1., -7.,  0.,  4.],
        [ 1.,  1.,  0.,  0., -1.,  0.,  3.],
        [ 1.,  1.,  0.,  0., -1., -1.,  0.]])

**Ejercicio** Transforme a la forma estándar los siguienes modelos.

**Modelo 1)**

Función objetivo:

$$\text{max } 2x_1 + 3x_2$$

Sujeto a:
$$ \begin{array}{cccc}
    x_1 & +2x_2 & \le & 6\\
   2x_1 & +x_2  & \le & 8\\
    x_1 &       & \ge & 8\\
        &   x_1, x_2    &  \ge & 0
  \end{array}$$

**Problema 2.**

Función objetivo:

$$\text{max } 3x_1 + 5x_2$$

Sujeto a:
$$ \begin{array}{cccc}
    x_1 &       & \ge &  5\\
        &  +x_2 & \le & 10\\
    x_1 & +2x_2 & \ge & 10\\
        & x_1, x_2    &  \ge & 0
  \end{array}$$

**Problema 3.**

Función objetivo:

$$\text{max } 40x_1 + 60x_2$$

Sujeto a:
$$ \begin{array}{cccc}
    2x_1 &  +x_2 & \le & 70\\
     x_1 &  +x_2 & \le & 40\\
     x_1 & +3x_2 & \le & 90\\
        & x_1, x_2    &  \ge & 0
  \end{array}$$

**Problema 4.**

Función objetivo:

$$\text{max } 3x_1 + 2x_2$$

Sujeto a:
$$ \begin{array}{cccc}
    6x_1 &  +4x_2 & \le & 24\\
     x_1 &        & \le & 3\\
        & x_1, x_2 &  \ge & 0
  \end{array}$$

Forma Estándar
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/04-forma-estandar.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/04-forma-estandar.ipynb) para ver la última versión online en `nbviewer`. 

---