Solución Básica Inicial
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/07-solucion-basica-inicial.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/07-solucion-basica-inicial.ipynb) para ver la última versión online en `nbviewer`. 

---

Para aplicar el método simplex es necesario obtener una solución básica inicial. A continuación se describe el método para su obtención. 

> **El problema solo tiene restricciones $\le$**. Se transforma el problema a la forma estándar agregando variables de holgura, las cuales conforman la base inicial. El problema se optimiza usando el simplex tal como se indicó.

> **El problema tiene restricciones $\ge$ o $=$**. Se transforma el problema a la forma estándar. Se agregan variables artificiales a dichas restricciones. La base esta conformada por las variables de holgura y las artificiales. La optimización se realiza en dos fases: en la primera fase se minimiza la suma de variables artificiales. Se retorna al problema original cuando todas las variables artificiales salen de la base y se continua la optimización como ya se explicó.

$$\text{max } z = x_1 + 3x_2$$

Sujeto a:
$$ 
\begin{array}{cccc}
   -x_1 &  +x_2 & \ge & 0\\
  -3x_1 &  +x_2 & \le & 3\\
   +x_1 & +2x_2 & =   & 6\\
\end{array}
$$   
   
   
   
$$x_1, x_2  \ge  0$$
  

In [61]:
import numpy as np
a = np.matrix('-1. 1 0; -3 1 3;  1 2 6; -1 -3 0')
a

matrix([[-1.,  1.,  0.],
        [-3.,  1.,  3.],
        [ 1.,  2.,  6.],
        [-1., -3.,  0.]])

**Paso 1.** Se lleva a la forma estándar.

$$ 
\begin{array}{cccccc}
   -x_1 &  +x_2 & -x_3 &      &    & = & 0\\
  -3x_1 &  +x_2 &      & +x_4 &    & = & 3\\
   +x_1 & +2x_2 &      &      &    & = & 6\\
   -x_1 & -3x_2 &      &      & -z & = & 0\\   
\end{array}
$$   
   
   

In [62]:
a = np.c_[a[:,[0,1]], np.matrix('-1; 0; 0; 0'), np.matrix('0; 1; 0; 0'), np.matrix('0; 0; 0; -1'), a[:, [2]]]
a

matrix([[-1.,  1., -1.,  0.,  0.,  0.],
        [-3.,  1.,  0.,  1.,  0.,  3.],
        [ 1.,  2.,  0.,  0.,  0.,  6.],
        [-1., -3.,  0.,  0., -1.,  0.]])

**Paso 2.** Se agregan las variables artificiales $x_5$ a la restricción 1 y $x_6$ a la restricción 3 para poder construir una solución básica factible inicial. Adicionalmente, se agrega una nueva función objetivo $w = x_5 + x_6$

$$ 
\begin{array}{ccccccc}
   -x_1 &  +x_2 & -x_3 &      & +x_5 &      &    &    & = & 0\\
  -3x_1 &  +x_2 &      & +x_4 &      &      &    &    & = & 3\\
   +x_1 & +2x_2 &      &      &      & +x_6 &    &    & = & 6\\
   -x_1 & -3x_2 &      &      &      &      & -z &    & = & 0\\   
        &       &      &      & +x_5 & +x_6 &    & -w & = & 0\\
\end{array}
$$   
   
   

In [63]:
a = np.c_[a[:,[0,1,2,3]], np.matrix('1; 0; 0; 0'), np.matrix('0; 0; 1; 0'), a[:, [4]], np.matrix('0; 0; 0; 0'), a[:, [-1]]]
a

matrix([[-1.,  1., -1.,  0.,  1.,  0.,  0.,  0.,  0.],
        [-3.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  3.],
        [ 1.,  2.,  0.,  0.,  0.,  1.,  0.,  0.,  6.],
        [-1., -3.,  0.,  0.,  0.,  0., -1.,  0.,  0.]])

In [64]:
a = np.r_[a, np.matrix('0 0 0 0 1 1 0 -1 0')]
a

matrix([[-1.,  1., -1.,  0.,  1.,  0.,  0.,  0.,  0.],
        [-3.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  3.],
        [ 1.,  2.,  0.,  0.,  0.,  1.,  0.,  0.,  6.],
        [-1., -3.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  1.,  0., -1.,  0.]])

**Paso 3.** En este punto no es posible aplicar el método simplex, ya que los coeficientes de $x_5$ y $x_6$ (que forman la base) son diferentes de cero. Se deben aplicar operaciones elementales para hacerlos cero en la última ecuación.

In [65]:
a[4,:] = a[4,:] - a[0,:] ## se elimina x5
a[4,:] = a[4,:] - a[2,:] ## se elimina x6
a

matrix([[-1.,  1., -1.,  0.,  1.,  0.,  0.,  0.,  0.],
        [-3.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  3.],
        [ 1.,  2.,  0.,  0.,  0.,  1.,  0.,  0.,  6.],
        [-1., -3.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0., -3.,  1.,  0.,  0.,  0.,  0., -1., -6.]])

$$ 
\begin{array}{ccccccc}
   -x_1 &  +x_2 & -x_3 &      & +x_5 &      &    &    & = &  0\\
  -3x_1 &  +x_2 &      & +x_4 &      &      &    &    & = &  3\\
   +x_1 & +2x_2 &      &      &      & +x_6 &    &    & = &  6\\
   -x_1 & -3x_2 &      &      &      &      & -z &    & = &  0\\   
        & -3x_2 & +x_3 &      &      &      &    & -w & = & -6\\
\end{array}
$$   
   
   

**Paso 4.** Se procede a aplicar el método simplex. $x_2$ entre en la base y $x_5$ sale de la base.

In [66]:
a[1,:] = a[1,:] -   a[0,:]   ## se elimina x2 de la restricción 2
a[2,:] = a[2,:] - 2*a[0,:]   ## se elimina x2 de la restricción 3
a[3,:] = a[3,:] + 3*a[0,:]   ## se elimina x2 de la restricción 4
a[4,:] = a[4,:] + 3*a[0,:]   ## se elimina x2 de la restricción 5
a

matrix([[-1.,  1., -1.,  0.,  1.,  0.,  0.,  0.,  0.],
        [-2.,  0.,  1.,  1., -1.,  0.,  0.,  0.,  3.],
        [ 3.,  0.,  2.,  0., -2.,  1.,  0.,  0.,  6.],
        [-4.,  0., -3.,  0.,  3.,  0., -1.,  0.,  0.],
        [-3.,  0., -2.,  0.,  3.,  0.,  0., -1., -6.]])

$$ 
\begin{array}{ccccccc}
   -x_1 &  +x_2 &  -x_3 &      &  +x_5 &      &    &    & = &  0\\
  -2x_1 &       &  +x_3 & +x_4 &  -x_5 &      &    &    & = &  3\\
  +3x_1 &       & +2x_3 &      & -2x_5 & +x_6 &    &    & = &  6\\
  -4x_1 &       & -3x_3 &      & +3x_5 &      & -z &    & = &  0\\   
  -3x_1 &       & -2x_3 &      & +3x_5 &      &    & -w & = & -6\\
\end{array}
$$   
   
   

**Paso 5.** $x_1$ entra a la base y sale $x_2$.

In [67]:
a[2,:] = a[2,:] / 3
a[0,:] = a[0,:] +   a[2,:]   ## se elimina x1 de la restricción 1
a[1,:] = a[1,:] + 2*a[2,:]   ## se elimina x1 de la restricción 2
a[3,:] = a[3,:] + 4*a[2,:]   ## se elimina x1 de la restricción 4
a[4,:] = a[4,:] + 3*a[2,:]   ## se elimina x1 de la restricción 5
a.round(3) 

array([[ 0.   ,  1.   , -0.333,  0.   ,  0.333,  0.333,  0.   ,  0.   ,  2.   ],
       [ 0.   ,  0.   ,  2.333,  1.   , -2.333,  0.667,  0.   ,  0.   ,  7.   ],
       [ 1.   ,  0.   ,  0.667,  0.   , -0.667,  0.333,  0.   ,  0.   ,  2.   ],
       [ 0.   ,  0.   , -0.333,  0.   ,  0.333,  1.333, -1.   ,  0.   ,  8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  1.   ,  0.   , -1.   ,  0.   ]])

$$ 
\begin{array}{ccccccc}
        &  +x_2 &  -\frac{1}{3}x_3 &      &  +\frac{1}{3}x_5 & +\frac{1}{3}x_6 &    &    & = &  2\\
        &       &  +\frac{7}{3}x_3 & +x_4 &  -\frac{7}{3}x_5 & +\frac{2}{3}x_6 &    &    & = &  7\\
   +x_1 &       &  +\frac{2}{3}x_3 &      &  -\frac{2}{3}x_5 & +\frac{1}{3}x_6 &    &    & = &  2\\
        &       &  -\frac{1}{3}x_3 &      &  +\frac{1}{3}x_5 & +\frac{4}{3}x_6 & -z &    & = &  8\\   
        &       &                  &      &  +x_5            & +x_6            &    & -w & = &  0\\
\end{array}
$$   
   
   

**Paso 6.** Ya que las variables artificiales salieron de la base, se puede eliminar la última ecuación y la variable $w$.

In [68]:
a = a[[0,1,2,3],:]                ## elimina la última fila
a = a[:,[0, 1, 2, 3, 4, 5, 6, 8]] ## elimina la columna correspondiente a 2
a.round(3)

array([[ 0.   ,  1.   , -0.333,  0.   ,  0.333,  0.333,  0.   ,  2.   ],
       [ 0.   ,  0.   ,  2.333,  1.   , -2.333,  0.667,  0.   ,  7.   ],
       [ 1.   ,  0.   ,  0.667,  0.   , -0.667,  0.333,  0.   ,  2.   ],
       [ 0.   ,  0.   , -0.333,  0.   ,  0.333,  1.333, -1.   ,  8.   ]])

$$ 
\begin{array}{ccccccc}
        &  +x_2 &  -\frac{1}{3}x_3 &      &  +\frac{1}{3}x_5 & +\frac{1}{3}x_6 &    & = &  2\\
        &       &  +\frac{7}{3}x_3 & +x_4 &  -\frac{7}{3}x_5 & +\frac{2}{3}x_6 &    & = &  7\\
   +x_1 &       &  +\frac{2}{3}x_3 &      &  -\frac{2}{3}x_5 & +\frac{1}{3}x_6 &    & = &  2\\
        &       &  -\frac{1}{3}x_3 &      &  +\frac{1}{3}x_5 & +\frac{4}{3}x_6 & -z & = &  8\\   
\end{array}
$$   
   
   

**Paso 7.** Se aplica el método simplex. $x_3$ entra en la base y reemplaza a $x_1$.

In [69]:
a[2,:] = 1.5 * a[2,:]
a[0,:] = a[0,:] + 1./3*a[2,:]
a[1,:] = a[1,:] - 7/3*a[2,:]
a[3,:] = a[3,:] + 1/3*a[2,:]
a.round(3)

array([[ 0.5,  1. , -0. ,  0. ,  0. ,  0.5,  0. ,  3. ],
       [-3.5,  0. , -0. ,  1. ,  0. , -0.5,  0. ,  0. ],
       [ 1.5,  0. ,  1. ,  0. , -1. ,  0.5,  0. ,  3. ],
       [ 0.5,  0. , -0. ,  0. ,  0. ,  1.5, -1. ,  9. ]])

$$ 
\begin{array}{ccccccc}
   +\frac{1}{2}x_1 &  +x_2 &       &      &       & +\frac{1}{2}x_6 &    & = &  3\\
   +\frac{7}{2}x_1 &       &       & +x_4 &       & -\frac{1}{2}x_6 &    & = &  0\\
   +\frac{3}{2}x_1 &       &  +x_3 &      &  -x_5 & +\frac{1}{2}x_6 &    & = &  3\\
   +\frac{1}{2}x_1 &       &       &      &       & +\frac{3}{2}x_6 & -z & = &  9\\   
\end{array}
$$   
   
   

**Paso 8.** Se llego a la solución óptima, puesto que todos los coeficientes de las variables no básicas ($x_1$, $x_4$, $x_5$, $x_6$) son iguales o mayores a cero. Ya que $x_4$ y $x_5$ tienen coeficiente cero en la última ecuación, existen múltiples soluciones. 

* El valor de la función objetivo es: $z= -9$.


* $x_2$ = 3.


* $x_1$ = 0, ya que no se encuentra en la base.

Solución Básica Inicial
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/metodos-y-modelos/blob/master/07-solucion-basica-inicial.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/metodos-y-modelos/blob/master/07-solucion-basica-inicial.ipynb) para ver la última versión online en `nbviewer`. 

---